version: '2'

services:
    db:
      image: mysql:5.7
      volumes:
        - db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: wordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      ports:
        - "8000:80"
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_PASSWORD: wordpress

    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin:latest
      ports:
         - "8001:80"
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
volumes:
    db_data:
